---
# Copyright (C) 2020      CipherMail B.V. <https://www.ciphermail.com/>
# Copyright (C) 2021      Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2020-2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

simplesamlphp__keyring__dependent_gpg_user: '{{ simplesamlphp__user }}'

simplesamlphp__keyring__dependent_gpg_keys:

  - user: '{{ simplesamlphp__user }}'
    group: '{{ simplesamlphp__group }}'
    home: '{{ simplesamlphp__home }}'
    id: '{{ simplesamlphp__upstream_git_gpg_key }}'

simplesamlphp__python__dependent_packages3:

  - 'python3-cryptography'

simplesamlphp__python__dependent_packages2:

  - 'python-cryptography'

simplesamlphp__ldap__dependent_tasks:

  - name: 'Create SimpleSAMLphp account for {{ simplesamlphp__ldap_device_dn | join(",") }}'
    dn: '{{ simplesamlphp__ldap_binddn }}'
    objectClass: '{{ simplesamlphp__ldap_self_object_classes }}'
    attributes: '{{ simplesamlphp__ldap_self_attributes }}'
    state: '{{ "present"
                if (simplesamlphp__ldap_enabled|bool and
                    simplesamlphp__ldap_device_dn|d())
                else "ignore" }}'

simplesamlphp__mariadb__dependent_databases:

  - name: '{{ simplesamlphp__mariadb_database }}'

simplesamlphp__mariadb__dependent_users:

  - user: '{{ simplesamlphp__mariadb_user }}'
    password: '{{ simplesamlphp__mariadb_password }}'
    database: '{{ simplesamlphp__mariadb_database }}'
    owner: '{{ simplesamlphp__user }}'
    group: '{{ simplesamlphp__group }}'
    home: '{{ simplesamlphp__home }}'

simplesamlphp__nginx__dependent_servers:

  - name: '{{ simplesamlphp__fqdn }}'
    filename: 'debops.simplesamlphp'
    root: '{{ simplesamlphp__application_root }}/www'
    webroot_create: False
    type: 'php'
    php_upstream: 'php_simplesamlphp'
    location_list:
      - pattern: '= /.well-known/openid-configuration'
        options: |
          rewrite ^(.*)$ /module.php/oidc/openid-configuration.php break;
          proxy_pass https://{{ simplesamlphp__fqdn }};
        state: 'present'
      - pattern: '/'
        options: 'try_files $uri $uri/ $uri.php;'

simplesamlphp__nginx__dependent_upstreams:

  - name: 'php_simplesamlphp'
    by_role: 'debops.simplesamlphp'
    type: 'php'
    php_pool: 'simplesamlphp'

simplesamlphp__php__dependent_packages:

  - '{{ [ "gmp" ]
        if "simplesamlphp/simplesamlphp-module-webauthn" in simplesamlphp__active_modules
        else [] }}'
  - 'json'
  - 'ldap'
  - 'mbstring'
  - '{{ [ "memcached" ]
        if (ansible_local.memcached.installed|d())|bool
        else [] }}'
  - '{{ [ "mysql" ]
        if simplesamlphp__mariadb_enabled|bool
        else [] }}'
  - 'xml'
  - 'zip'

simplesamlphp__php__dependent_pools:

  - name: 'simplesamlphp'
    by_role: 'debops.simplesamlphp'
    user: '{{ simplesamlphp__user }}'
    group: '{{ simplesamlphp__group }}'
    owner: '{{ simplesamlphp__user }}'
    home: '{{ simplesamlphp__home }}'
