---
# Copyright (C) 2021 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

simplesamlphp__original_metadata:

  - name: 'saml20-idp-hosted.php'
    type: 'metadata'
    comment: |
      SAML 2.0 IdP configuration for SimpleSAMLphp.

      See: https://simplesamlphp.org/docs/stable/simplesamlphp-reference-idp-hosted
    options:

      - name: '__DYNAMIC:1__'
        raw: |
          $metadata['__DYNAMIC:1__'] = [
              /*
               * The hostname of the server (VHOST) that will use this SAML entity.
               *
               * Can be '__DEFAULT__', to use this entry by default.
               */
              'host' => '__DEFAULT__',

              // X.509 key and certificate. Relative to the cert directory.
              'privatekey' => 'server.pem',
              'certificate' => 'server.crt',

              /*
               * Authentication source to use. Must be one that is configured in
               * 'config/authsources.php'.
               */
              'auth' => 'example-userpass',

              /* Uncomment the following to use the uri NameFormat on attributes. */
              /*
              'attributes.NameFormat' => 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',
              'authproc' => [
                  // Convert LDAP names to oids.
                  100 => ['class' => 'core:AttributeMap', 'name2oid'],
              ],
              */

              /*
               * Uncomment the following to specify the registration information in the
               * exported metadata. Refer to:
               * http://docs.oasis-open.org/security/saml/Post2.0/saml-metadata-rpi/v1.0/cs01/saml-metadata-rpi-v1.0-cs01.html
               * for more information.
               */
              /*
              'RegistrationInfo' => [
                  'authority' => 'urn:mace:example.org',
                  'instant' => '2008-01-17T11:28:03Z',
                  'policies' => [
                      'en' => 'http://example.org/policy',
                      'es' => 'http://example.org/politica',
                  ],
              ],
              */
          ];
        state: 'present'

  - name: 'saml20-idp-remote.php'
    type: 'metadata'
    comment: |
      SAML 2.0 remote IdP metadata for SimpleSAMLphp.

      Remember to remove the IdPs you don't use from this file.

      See: https://simplesamlphp.org/docs/stable/simplesamlphp-reference-idp-remote
    state: 'present'

  - name: 'saml20-sp-remote.php'
    type: 'metadata'
    comment: |
      SAML 2.0 remote SP metadata for SimpleSAMLphp.

      See: https://simplesamlphp.org/docs/stable/simplesamlphp-reference-sp-remote
    options:

      - name: 'https://saml2sp.example.org'
        comment: 'Example SimpleSAMLphp SAML 2.0 SP'
        data:
          - AssertionConsumerService: 'https://saml2sp.example.org/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp'
            SingleLogoutService:      'https://saml2sp.example.org/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp'

      - name: 'google.com'
        comment: |
          This example shows an example config that works with G Suite (Google Apps) for education.
          What is important is that you have an attribute in your IdP that maps to the local part of the email address at
          G Suite. In example, if your Google account is foo.com, and you have a user that has an email john@foo.com, then you
          must set the simplesaml.nameidattribute to be the name of an attribute that for this user has the value of 'john'.
        data:
          - AssertionConsumerService: 'https://www.google.com/a/g.feide.no/acs'
            NameIDFormat: 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'
            simplesaml.nameidattribute: 'uid'
            simplesaml.attributes: False
        separator: True

      - name: 'https://legacy.example.edu'
        raw: |
          $metadata['https://legacy.example.edu'] = [
              'AssertionConsumerService' => 'https://legacy.example.edu/saml/acs',
              /*
               * Currently, SimpleSAMLphp defaults to the SHA-256 hashing algorithm.
               * Uncomment the following option to use SHA-1 for signatures directed
               * at this specific service provider if it does not support SHA-256 yet.
               *
               * WARNING: SHA-1 is disallowed starting January the 1st, 2014.
               * Please refer to the following document for more information:
               * http://csrc.nist.gov/publications/nistpubs/800-131A/sp800-131A.pdf
               */
              //'signature.algorithm' => 'http://www.w3.org/2000/09/xmldsig#rsa-sha1',
          ];
        state: 'present'
        separator: True


simplesamlphp__metadata: []

simplesamlphp__group_metadata: []

simplesamlphp__host_metadata: []

simplesamlphp__combined_metadata: '{{ simplesamlphp__original_metadata
                                      + simplesamlphp__metadata
                                      + simplesamlphp__group_metadata
                                      + simplesamlphp__host_metadata }}'
