---

dependencies:

  - role: debops.ansible_plugins

galaxy_info:

  role_name: 'docker_registry'
  author: 'Maciej Delmanowski'
  description: 'Install and manage Docker Registry service'
  company: 'DebOps'
  license: 'GPL-3.0'
  min_ansible_version: '2.4.0'
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - docker
    - containers
