---
# Copyright (C) 2016-2017 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2023      Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016-2023 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: Manage and configure the Apache HTTP Server
  hosts: [ 'debops_service_apache' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  vars:
    ferm__dependent_rules:
      - '{{ apache__ferm__dependent_rules }}'

  tasks:

    - name: Prepare apache environment
      ansible.builtin.import_role:
        name: 'debops.debops.apache'
        tasks_from: 'main_env'
      tags: [ 'role::apache', 'role::apache:env' ]

    - name: Configure ferm firewall
      ansible.builtin.import_role:
        name: 'debops.debops.ferm'
      tags: [ 'role::ferm', 'skip::ferm' ]

    - name: Install and configure Apache
      ansible.builtin.import_role:
        name: 'debops.debops.apache'
      tags: [ 'role::apache', 'skip::apache' ]
