---
# Copyright (C) 2021 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2021 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

one_core__version: '{{ ansible_local.opennebula.version | d("0.0.0") }}'

one_core__base_packages: [ 'opennebula' ]

one_core__packages: []

one_core__user: 'oneadmin'

one_core__group: 'oneadmin'

one_core__home: '/var/lib/one'

one_core__admin_sshkeys: '{{ lookup("pipe", "ssh-add -L | grep ^\\\(sk-\\\)\\\?ssh || cat ~/.ssh/*.pub || true") }}'

one_core__database_server: '{{ ansible_local.mariadb.server | d("localhost") }}'

one_core__database_user: 'oneadmin'

one_core__database_name: 'opennebula'

one_core__database_password: "{{ lookup('password', secret + '/mariadb/' +
                                 (ansible_local.mariadb.delegate_to | d(inventory_hostname)) +
                                 '/credentials/' + one_core__database_user +
                                 '/password length=48') }}"
